version: '3.3'
services:
    uploadapp:
        build:
            context: ./uploadapp 
            dockerfile: Dockerfile
        ports:
            - "8050:80"
        depends_on:
                - ipfs

    ipfs:
        image: ipfs/go-ipfs:v0.7.0
        ports:
            - "5001:5001"
            - "3000:3000"
            - "8080:8080"
        
